# Generated by Django 3.0.8 on 2020-07-26 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passangers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
