# Generated by Django 3.0.8 on 2020-08-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_remove_trip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cell_number',
            field=models.IntegerField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inst_username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
