# Generated by Django 3.0.8 on 2020-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20200812_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.IntegerField(null=True),
        ),
    ]
