# Generated by Django 3.0.8 on 2020-08-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
