# Generated by Django 3.0.8 on 2020-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20200812_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
