# Generated by Django 3.0.8 on 2020-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_auto_20200812_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='inst_username',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cell_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
