dist: bionic

language: python

services:
  - postgresql

addons:
  postgresql: "9.6"
  # https://gis.stackexchange.com/a/252610
  # apt:
  #   packages:
  #     - postgresql-9.6-postgis-2.3

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION='Django>=1.11,<1.12'
  - DJANGO_VERSION='Django>=2.2,<2.3'
  - DJANGO_VERSION='Django>=3.0,<3.1'
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

matrix:
  allow_failures:
    - python: "3.8"
      env: DJANGO_VERSION='Django>=1.11,<1.12'
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

before_install:
  # https://gis.stackexchange.com/a/252610
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get install --yes postgresql-9.6-postgis-2.4

install:
  - pip install $DJANGO_VERSION
  - pip install -q django-model-utils flake8 psycopg2 six swapper tox tqdm

before_script:
  # - psql -U postgres -c "CREATE EXTENSION postgis;"
  - psql -c 'create database django_cities;' -U postgres
  - psql -U postgres -c 'CREATE EXTENSION postgis;' -d django_cities

script:
  - flake8
  - PYTHONPATH=. python test_project/manage.py test test_app --noinput
